### ISSUE TITLE
XCode 12 build warning, minimum deployment target

### ISSUE THREAD

**Issue by drmarkpowell** [seaburg/IGIdenticon#14]
XCode 12 warning on build:
... SourcePackages/checkouts/IGIdenticon/Package.swift The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99.

Consider bumping the minimum deployment target to 9.0 to address the warning? (Package.swift)

**Comment by seaburg** [comment]
Fixed. Thanks you!
