### ISSUE TITLE
Mac Carthage support

### ISSUE THREAD

**Issue by kengruven** [seaburg/IGIdenticon#8]
This looks like a pretty neat library, and I'm happy to see it has both iOS and Mac support in the source code.

Unfortunately the default scheme (I think?) only builds for iOS, so a Mac application that loads it with Carthage doesn't build a Mac framework.

This is probably easy to fix, and I'll take a look if I have time, but Xcode projects are not exactly my forte.

**Comment by seaburg** [comment]
Fixed. Thank you!

**Comment by kengruven** [comment]
That was fast, thanks!

I can't seem to get it to work, though.  The changeset looks reasonable to me, and `carthage update --platform iOS` works fine, but `carthage update --platform Mac --verbose` gives:

```
*** Checking out IGIdenticon at "0.4.1"
*** Building scheme "Identicon macOS" in Identicon.xcodeproj
/usr/bin/xcrun xcodebuild -project /Users/ken/X/Carthage/Checkouts/IGIdenticon/Identicon.xcodeproj -scheme Identicon macOS -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

xcodebuild: error: Failed to build project Identicon with scheme Identicon macOS.
	Reason: The run destination My Mac is not valid for Running the scheme 'Identicon macOS'.
A shell task (/usr/bin/xcrun xcodebuild -project /Users/ken/X/Carthage/Checkouts/IGIdenticon/Identicon.xcodeproj -scheme Identicon macOS -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 70:
xcodebuild: error: Failed to build project Identicon with scheme Identicon macOS.
	Reason: The run destination My Mac is not valid for Running the scheme 'Identicon macOS'.
```

Am I missing something?

(The tvOS and watchOS schemes don't work for me, either, but I don't need them, and the errors are completely different.  They seem related to simulators, which I probably don't have installed.)

**Comment by seaburg** [comment]
> The tvOS and watchOS schemes don't work for me

I'm sorry, I forgot update `TARGETED_DEVICE_FAMILY`

> carthage update --platform Mac --verbose
You use Xcode 9?

**Comment by seaburg** [comment]
I removed hardcoded skd version. This was to solve the problem

**Comment by kengruven** [comment]
(I'm still on Xcode 8.2.1.)

The 0.4.2 release now builds without error, for all 4 platforms.  Thank you!
